/*
 * SSD1306.h
 *
 * Created: 09/07/2025 12:20:04
 *  Author: igwnu
 */ 


#ifndef SSD1306_H_
#define SSD1306_H_

//SETUP
#define CHARGE_PUMP_SETTING					0x8D
	#define CHARGE_PUMP_ENABLE				0x14
	#define  CHARGE_PUMP_DISABLE			0x10

#define SET_DISPLAY_ON						0xAF
#define SET_DISPLAY_OFF						0xAE

//FUNDAMENTAL COMMAND TABLE
#define SET_CONTRAST_CONTROL				0x81
	#define SET_CONTRAST_CONTROL_RESET		0x7F
	
#define ENTIRE_DISPLAY_ON					0xA5	//TEST MODE
#define ENTIRE_DISPLAY_OFF					0xA4	//RESET (TURN OFF TEST MODE)

#define SET_NORMAL_DISPLAY					0xA6
#define SET_INVERSE_DISPLAY					0xA7	

//ZAPYTAC PANA O  TE RAM ON I OFF'Y

//ADDRESSING SETTING COMMAND TABLE
#define SET_MEMORY_ADDRESSING_MODE			0x20
	#define	HORIZONTAL_ADDRESSING_MODE		0b00
	#define VERTICAL_ADDRESSING_MODE		0b01
	#define PAGE_ADDRESSING_MODE_RESET		0b10



#endif /* SSD1306_H_ */