/*
 * spi.c
 *
 * Created: 01/04/2025 18:49:32
 *  Author: igwnu
 */ 

#include <avr/io.h>


void spi_ini(void)
{
		PORTA.DIRSET = PIN7_bm | PIN4_bm | PIN6_bm;				//SETTING THE SS PIN TO OUTPUT, SO THE MICROCONTROLLER WILL BE THE MASTER (THE SS PIN), SETTING MOSI & SCK TO OUTPUT SO THAT THERE'S A TRANSFER AVAILABLE
		PORTA.OUTSET = PIN7_bm;									//SETTING PA7 TO HIGH STATE SO IT DOESNT START A DATA TRANSMIT INSTANTLY AFTER TURNING ON THE PROGRAM
		SPI0.CTRLA |= SPI_MASTER_bm;							//SETTING UP SPI HOST MODE
		SPI0.CTRLA |= SPI_PRESC_DIV64_gc;						//SETTING UP THE PRESCALER
		SPI0.CTRLA |= SPI_ENABLE_bm;							//ENABLING SPI
}

void spi_sendByte(char x)
{	
	SPI0.DATA = x;							//WYSYLANIE DANYCH
	while(!(SPI0.INTFLAGS & SPI_IF_bm));	//STANDBY LOOP - WAITS UNTIL THE SHIFT REGISTER IS EMPTY SO THAT NO BYTE IS OVERWRITTEN
	SPI0.DATA = x;							//WYSYLANIE DANYCH
	while(!(SPI0.INTFLAGS & SPI_IF_bm));	//STANDBY LOOP - WAITS UNTIL THE SHIFT REGISTER IS EMPTY SO THAT NO BYTE IS OVERWRITTEN
	
	PORTA.OUTSET = PIN7_bm;					//TOGGLE THE PA7 PIN SO THAT WE KNOW A BYTE HAS BEEN SENT
	PORTA.OUTCLR = PIN7_bm;					
}
